// <auto-generated />
using System;
using DrugStore.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugStore.API.Migrations
{
    [DbContext(typeof(DrugStoreDbContext))]
    partial class DrugStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DrugStore.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Placeholder Category Description",
                            Name = "Placeholder Category Name"
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InsurancesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("InsurancesId");

                    b.HasIndex("Name", "Ssn");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Placeholder Customer Address",
                            Description = "Placeholder Customer Description",
                            Email = "PlaceholderCustomer@Email.com",
                            InsurancesId = 1,
                            Name = "Placeholder Customer Name",
                            Phone = "0000000000",
                            Ssn = "000000000",
                            ZipCode = "00000"
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Insurance");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Placeholder Insurance Description",
                            Name = "Placeholder Insurance Name"
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("SuppliersId");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 3, 26, 14, 22, 34, 585, DateTimeKind.Local).AddTicks(4023),
                            Description = "Placeholder Invoice Description",
                            SuppliersId = 1
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("money");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("Name");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriesId = 1,
                            Description = "Placeholder Product Description",
                            Name = "Placeholder Product Name",
                            PurchasePrice = 10m,
                            SalePrice = 20m
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.ProductInvoice", b =>
                {
                    b.Property<int>("InvoicesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InvoicesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.HasIndex("Quantity");

                    b.ToTable("ProductInvoice");

                    b.HasData(
                        new
                        {
                            InvoicesId = 1,
                            ProductsId = 1,
                            Description = "Placeholder ProductInvoice Description",
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.ProductReceipt", b =>
                {
                    b.Property<int>("ReceiptsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ReceiptsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.HasIndex("Quantity");

                    b.ToTable("ProductReceipt");

                    b.HasData(
                        new
                        {
                            ReceiptsId = 1,
                            ProductsId = 1,
                            Description = "Placeholder ProductReceipt Description",
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomersId");

                    b.HasIndex("Date");

                    b.ToTable("Receipt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomersId = 1,
                            Date = new DateTime(2023, 3, 26, 14, 22, 34, 585, DateTimeKind.Local).AddTicks(4131),
                            Description = "Placeholder Receipt Description"
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ein")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Ein");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Placeholder Supplier Address",
                            Description = "Placeholder Supplier Description",
                            Ein = "000000000",
                            Email = "PlaceholderSupplier@Email.com",
                            Name = "Placeholder Supplier Name",
                            Phone = "0000000000",
                            ZipCode = "00000"
                        });
                });

            modelBuilder.Entity("DrugStore.API.Entities.Customer", b =>
                {
                    b.HasOne("DrugStore.API.Entities.Insurance", "Insurances")
                        .WithMany()
                        .HasForeignKey("InsurancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurances");
                });

            modelBuilder.Entity("DrugStore.API.Entities.Invoice", b =>
                {
                    b.HasOne("DrugStore.API.Entities.Supplier", "Suppliers")
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("DrugStore.API.Entities.Product", b =>
                {
                    b.HasOne("DrugStore.API.Entities.Category", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DrugStore.API.Entities.ProductInvoice", b =>
                {
                    b.HasOne("DrugStore.API.Entities.Invoice", "Invoices")
                        .WithMany("ProductInvoice")
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugStore.API.Entities.Product", "Products")
                        .WithMany("ProductInvoice")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DrugStore.API.Entities.ProductReceipt", b =>
                {
                    b.HasOne("DrugStore.API.Entities.Product", "Products")
                        .WithMany("ProductReceipt")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugStore.API.Entities.Receipt", "Receipts")
                        .WithMany("ProductReceipt")
                        .HasForeignKey("ReceiptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("DrugStore.API.Entities.Receipt", b =>
                {
                    b.HasOne("DrugStore.API.Entities.Customer", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("DrugStore.API.Entities.Invoice", b =>
                {
                    b.Navigation("ProductInvoice");
                });

            modelBuilder.Entity("DrugStore.API.Entities.Product", b =>
                {
                    b.Navigation("ProductInvoice");

                    b.Navigation("ProductReceipt");
                });

            modelBuilder.Entity("DrugStore.API.Entities.Receipt", b =>
                {
                    b.Navigation("ProductReceipt");
                });
#pragma warning restore 612, 618
        }
    }
}
